# Limine config for Arch Linux + FreeBSD for BIOS/GPT

timeout: 5
verbose: yes
interface_resolution: 1280x800

term_palette: 191724;eb6f92;9ccfd8;f6c177;31748f;c4a7e7;9ccfd8;e0def4
term_palette_bright: 6e6a86;eb6f92;9ccfd8;f6c177;31748f;c4a7e7;9ccfd8;e0def4
term_background: 191724
term_foreground: e0def4
term_background_bright: 6e6a86
term_foreground_bright: e0def4

/Arch Linux
        protocol: linux
        path: boot():/vmlinuz-linux-lts
        cmdline: root=UUID=ae010e5c-bfd1-48d0-ac1b-8b147d6e68a6 rw nvidia-drm.modeset=1 usbcore.autosuspend=-1
        module_path: boot():/intel-ucode.img
        module_path: boot():/initramfs-linux-lts.img
        resolution: 1280x800

/FreeBSD
        protocol: bios
        drive: 1
	partition: 5

/Memtest86+
        protocol: linux
        path: boot():/memtest86+/memtest.bin
