[mgr]
ratio          = [1, 4, 4]
sort_by        = "mtime"
sort_sensitive = true
sort_reverse   = true
sort_dir_first = true
show_hidden    = true
show_symlink   = true
linemode = "size_and_mtime"

[plugin]
prepend_preloaders = [
  # Do not preload files in mounted locations:
  # Environment variable won't work here.
  # Using absolute path instead.
  { url = "/run/user/1000/gvfs/**/*", run = "noop" },

  # For mounted hard disk/drive
  { url = "/run/media/yorkfield/**/*", run = "noop" },
]
prepend_previewers = [
  # Allow to preview folder.
  { url = "*/", run = "folder" },

  # Do not previewing files in mounted locations.
  # Uncomment the line below to allow previewing text files.
  # { mime = "{text/*,application/x-subrip}", run = "code" },

  # Using absolute path.
  { url = "/run/user/1000/gvfs/**/*", run = "noop" },

  # For mounted hard disk/drive.
  { url = "/run/media/yorkfield/**/*", run = "noop" },
]

prepend_fetchers = [
  { id = "ffmpeg_stats", url = "*", run = "ffmpeg-stats", group = "hover" }
]

[opener]
play = [
	{ run = 'mpv "$@"', orphan = true, desc = "Play with mpv", for = "unix" }
]
edit = [
	{ run = 'vim "$@"', orphan = true, block = true, desc = "Edit with Vim", for = "unix" }
]
open = [
	{ run = 'xdg-open "$@"', orphan = true, desc = "Open with system default", for = "unix" }
]
view = [
  { run = 'nsxiv -a "$@"', orphan = true, desc = "View with nsxiv", for = "unix" }
]

[open]
rules = [
	{ mime = "video/*", use = "play" },
	{ mime = "audio/*", use = "play" },
	{ mime = "text/*", use = "edit" },
	{ mime = "image/*", use = "view" },
	{ mime = "*", use = "open" },
]
