[main]
include=/usr/share/foot/themes/noirblaze
# panda
# noirblaze
# starlight
# srcery
# visibone
# xterm
font=HurmitNerdFontMono-Regular:size=15
initial-window-mode=maximized
line-height=30px

[csd]
preferred=server
border-width=0
border-color=ff000000

[cursor]
style=underline
